#!/bin/bash

# for the University of Illinois
# 2022
# Michael Neill Hartman

# flic2_server

sudo pkill -f flicd

START=`pwd`
cd ${START}/fliclib-linux-hci-master/bin/x86_64

sudo setcap cap_net_admin=ep ./flicd

[[ -e flic.sqlite3 ]] && rm flic.sqlite3

sudo rfkill unblock bluetooth

./flicd -f devices
