#!/bin/bash

# Copyright (c) 2022 Michael Neill Hartman. All rights reserved.
# mnh_license@proton.me
# https://github.com/hartmanm

# flic2_server

sudo pkill -f flicd

START=`pwd`
cd ${START}/fliclib-linux-hci/bin/x86_64

sudo chmod +x flicd

sudo setcap cap_net_admin=ep ./flicd

[[ -e flic.sqlite3 ]] && rm flic.sqlite3

sudo rfkill unblock bluetooth

./flicd -f devices
