#!/bin/bash

# Copyright (c) 2022 Michael Neill Hartman. All rights reserved.
# mnh_license@proton.me
# https://github.com/hartmanm

# flic2_delete_devices

START=$(dirname `readlink -f $0`)
cd ${START}/fliclib-linux-hci/bin/x86_64

[[ -e flic.sqlite3 ]] && rm flic.sqlite3

[[ -e devices ]] && rm devices