#!/bin/bash

# for the University of Illinois
# 2022
# Michael Neill Hartman

# flic2_delete_devices

START=$(dirname `readlink -f $0`)
cd ${START}/fliclib-linux-hci-master/bin/x86_64

[[ -e flic.sqlite3 ]] && rm flic.sqlite3

[[ -e devices ]] && rm devices