#!/bin/bash

# Copyright (c) 2022 Michael Neill Hartman. All rights reserved.
# mnh_license@proton.me
# https://github.com/hartmanm

# local_frontend_launcher

START=$(dirname `readlink -f $0`)
USE_FIREFOX_OR_CHROME=`bash get_json_key_value ${START}/m11.json USE_FIREFOX_OR_CHROME`

START=`pwd`
cp ${START}/modified_fliclib_linux_hci_sdk_overlays/index.html ${START}/fliclib-linux-hci/clientlib/websocket/client

sleep 2

[[ ${USE_FIREFOX_OR_CHROME} == "google-chrome" ]] && {
${USE_FIREFOX_OR_CHROME} file://${START}/fliclib-linux-hci/clientlib/websocket/client/index.html --no-sandbox
}
[[ ${USE_FIREFOX_OR_CHROME} == "firefox" ]] && {
${USE_FIREFOX_OR_CHROME} file://${START}/fliclib-linux-hci/clientlib/websocket/client/index.html
}
